### ISSUE TITLE
mis-posting

### ISSUE THREAD

**Issue by t-mashimo** [criteo/marathon-capabilities-plugin#10]
（mis-posting）

**Comment by kamaradclimber** [comment]
Hello, 
I'm not sure to understand this comment. Translated with google translate your message seems to talk about font size which.
I'll close the ticket

**Comment by t-mashimo** [comment]
I am very sorry for any inconvenience this may have caused. This post was meant to be made elsewhere by me. (I've never even seen your project here, so I'm wondering how it got posted here)
