### ISSUE TITLE
Do you have an example on how to configure the marathon task.

### ISSUE THREAD

**Issue by f1-outsourcing** [criteo/marathon-capabilities-plugin#3]
I am not getting this to work with marathon 1.8 and mesos 1.9.  From the code I can see you have to put this in labels, but what label name etc.

**Comment by kamaradclimber** [comment]
Hello, 

https://github.com/criteo/marathon-capabilities-plugin/blob/master/src/main/scala/com/criteo/marathon/CapabilitiesPlugin.scala#L14 shows that you need to define labels `MESOS_BOUNDING_CAPABILITIES` and/or `MESOS_EFFECTIVE_CAPABILITIES`
