### ISSUE TITLE
"You can't comment at this time. " on issues

### ISSUE THREAD

**Issue by f1-outsourcing** [criteo/marathon-capabilities-plugin#5]
I think some privileges need to be set, looks like I am not allowed to comment?

**Comment by kamaradclimber** [comment]
I don't see any special github permission to comment on github issues.
I actually would not understand why there would be a setting to allow new issues but no reply. Could you make sure you don't have an ad-blocker activated (on github + with criteo names, it sometimes give surprising behaviors)

**Comment by f1-outsourcing** [comment]
.

**Comment by f1-outsourcing** [comment]
How did you know???  Indeed ublock, pffff,  I would never have guessed

**Comment by kamaradclimber** [comment]
Simply because i have an adblocker as well

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by hiyyg** [comment]
I also met this problem. I can not comment using Microsoft Edge, but if I change to other browsers, it works.

**Comment by deepakinfoweb** [comment]
Thank you, BanKers, for your response.

We have also added **parent_ad_group_criterion**  in the request. Still, We are getting the error The required field was not present.

Request input json :
[{"create": {
        "resource_name": "customers/7370860149/adGroupCriteria/125570209334~-1",
        "status": "ENABLED",
        "listing_group": {
            "type_": "UNIT",
            "case_value": {
                "product_item_id": {
                    "value": "4309645"
                }
            },
            "parent_ad_group_criterion": "customers/7370860149/adGroupCriteria/125570209334~-1"
        }
    }}]

Response : 

Request made: ClientCustomerId: 7370860149, Host: googleads.googleapis.com, Method: /google.ads.googleads.v8.services.AdGroupCriterionService/MutateAdGroupCriteria, RequestId: ML0n3nvxfc6VX1TNxmoTcA, IsFault: True, FaultMessage: Listing group referenced in the operation was not found in the ad group.
Request with ID 'ML0n3nvxfc6VX1TNxmoTcA' failed with status 'INVALID_ARGUMENT' and includes the following errors:
        Error with message 'Listing group referenced in the operation was not found in the ad group.'.
                On field: operations
                On field: create
                On field: listing_group
                On field: parent_ad_group_criterion

**Comment by dxdtz** [comment]
1

**Comment by realJustinLee** [comment]
Perhaps just network issues?

**Comment by wangxingzhen** [comment]
w

**Comment by LeozaCEO2** [comment]
I am having this issue now after a few months

**Comment by kamaradclimber** [comment]
Have you tried to deactivate your ad-blocker (see https://github.com/criteo/marathon-capabilities-plugin/issues/5#issuecomment-541551071) to see if it changes something?
It's a very common issue with any url having `criteo` in its path.

**Comment by jcollum-nutrien** [comment]
This will also happen if github systems are down. Just happened to me about 20 minutes ago.

**Comment by mason-at-pieces** [comment]
Same ^, very odd

**Comment by LeozaCEO2** [comment]
it's only on one repository though, before it was on multiple

**Comment by simeyla** [comment]
Check https://downdetector.com/status/github/ or https://www.githubstatus.com/

**Comment by LeozaCEO2** [comment]
Actually I think that the repo owner blocked me

**Comment by Lqp1** [comment]
You should probably try with a fresh browser profile, with no extension, etc...
As said in a previous comment, urls with `criteo` in it can be blocked by different privacy plugin. If you make it work without any extension, you should try to allow all urls from github.com for example.

In all cases, you are not blocked from this repo from what I see here

**Comment by LeozaCEO2** [comment]
Thanks, I'll check it out.

**Comment by tanerochris** [comment]
fg
